target 'Basic' do
  pod 'React', subspecs: [
    'RCTActionSheet',
    'RCTGeolocation',
    'RCTImage',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ], path: '../node_modules/react-native'

  pod 'react-native-opentok',  path: '../../../'
end
